const elements = [
    {
        name: "Fire",
        icon: "./src/assets/iconElementFire.png",
    },
    {
        name: "Ice",
        icon: "./src/assets/iconElementIce.png",
    },
    {
        name: "Imaginary",
        icon: "./src/assets/iconElementImaginary.png",
    },
    {
        name: "Lightning",
        icon: "./src/assets/iconElementLightning.png",
    },
    {
        name: "Physical",
        icon: "./src/assets/iconElementPhysical.png",
    },
    {
        name: "Quantum",
        icon: "./src/assets/iconElementQuantum.png",
    },
    {
        name: "Wind",
        icon: "./src/assets/iconElementWind.png",
    }
];

const paths = [
    {
        name: "Abundance",
        icon: "./src/assets/iconPathAbundance.png",
    },
    {
        name: "Destruction",
        icon: "./src/assets/iconPathDestruction.png",
    },
    {
        name: "Erudition",
        icon: "./src/assets/iconPathErudition.png",
    },
    {
        name: "Harmony",
        icon: "./src/assets/iconPathHarmony.png",
    },
    {
        name: "Hunt",
        icon: "./src/assets/iconPathHunt.png",
    },
    {
        name: "Nihility",
        icon: "./src/assets/iconPathNihility.png",
    },
    {
        name: "Preservation",
        icon: "./src/assets/iconPathPreservation.png",
    },
];

const banners = [
    {
        title: "Buterfly on Swordtip",
        characterName: "Seele",
        path: "Hunt",
        element: "Quantum",
        img: "./src/img/Seele.png",
        releaseVersion: "1.0",
        phase: 1,
        reruns:[
            {
                version: "1.4",
                phase: 2,
                date:"2023-10-27 ~ 2023-11-15",
            },
        ],
        releaseDate: "2023-04-26 ~ 2023-05-17",
        character4star: ["Hook", "Natasha", "Pela"],
        lightCone: "In the night",
    },
    {
        title: "Swirl of Heavenly Spear",
        characterName: "Jing Yuan",
        path: "Erudition",
        element: "Lightning",
        img: "./src/img/JingYuan.png",
        releaseVersion: "1.0",
        phase: 2,
        reruns:[
            {
                version: "2.0",
                phase: 2,
                date:"2024-02-29 ~ 2024-03-26",
            },
        ],
        releaseDate: "2023-05-17 ~ 2023-06-07",
        character4star: ["7 de Março", "Sushang", "Tingyun"],
        lightCone: "Before Dawn",
    },
    {
        title: "Contract Zero",
        characterName: "Loba Prateada",
        path: "Nihility",
        element: "Quantum",
        img: "./src/img/LobaPrateada.png",
        releaseVersion: "1.1",
        phase: 1,
        reruns:[
            {
                version: "1.5",
                phase: 2,
                date:"2023-12-06 ~ 2023-12-26",
            },
        ],
        releaseDate: ["2023-06-07 ~ 2023-06-28"],
        character4star: ["Asta", "Dan Heng", "Serval"],
        lightCone: "Incessant Rain",
    },
    {
        title: "Laic Pursuit",
        characterName: "Luocha",
        path: "Abundance",
        element: "Imaginary",
        img: "./src/img/Luocha.png",
        releaseVersion: "1.1",
        phase: 2,
        reruns:[
            {
                version: "2.1",
                phase: 1,
                date:"2024-03-26 ~ 2024-04-17",
            },
        ],
        releaseDate: ["2023-06-28 ~ 2023-07-18"],
        character4star: ["Pela", "Qingque", "Yukong"],
        lightCone: "Echoes of the Coffin",
    },
    {
        title: "A Lost Soul",
        characterName: "Blade",
        path: "Destruction",
        element: "Wind",
        img: "./src/img/Blade.png",
        releaseVersion: "1.2",
        phase: 1,
        reruns:[
            {
                version: "1.6",
                phase: 1,
                date:"2023-12-26 ~ 2024-01-17",
            },
        ],
        releaseDate: ["2023-07-18 ~ 2023-08-09"],
        character4star: ["Arlan", "Natasha", "Sushang"],
        lightCone: "The Unreachable Side",
    },
    {
        title: "Nessun Norma",
        characterName: "Kafka",
        path: "Nihility",
        element: "Lightning",
        img: "./src/img/Kafka.png",
        releaseVersion: "1.2",
        phase: 2,
        reruns:[
            {
                version: "1.6",
                phase: 2,
                date:"2024-01-17 ~ 2024-02-05",
            },
            {
                version: "2.5",
                phase: 1,
                date:"2024-09-09 ~ 2024-10-02",
            },
        ],
        releaseDate: ["2023-08-09 ~ 2023-08-29"],
        character4star: ["Luka", "Sampo", "Serval"],
        lightCone: "Patience Is All You Need",
    },
    {
        title: "Epochal Spectrum",
        characterName: "Imbibitor Lunae",
        path: "Destruction",
        element: "Imaginary",
        img: "./src/img/ImbibitorLunae.png",
        releaseVersion: "1.3",
        phase: 1,
        reruns:[
            {
                version: "2.0",
                phase: 1,
                date:"2024-02-05 ~ 2024-02-29",
            },
            {
                version: "2.6",
                phase: 1,
                date:"2024-10-22 ~ 2024-11-13",
            },
        ],
        releaseDate: ["2023-08-29 ~ 2023-09-20"],
        character4star: ["Asta", "7 de Março", "Yukong"],
        lightCone: "Brighter Than the Sun",
    },
    {
        title: "Foreseen, Foreknown, Foretold",
        characterName: "Fu Xuan",
        path: "Preservation",
        element: "Quantum",
        img: "./src/img/FuXuan.png",
        releaseVersion: "1.3",
        phase: 2,
        reruns:[
            {
                version: "2.2",
                phase: 2,
                date:"2024-05-29 ~ 2024-06-18",
            },
        ],
        releaseDate: ["2023-09-20 ~ 2023-10-11"],
        character4star: ["Hook", "Hook", "Pela"],
        lightCone: "She Already Shut Her Eyes",
    },
    {
        title: "Gentle Eclipse of the Moon",
        characterName: "Jingliu",
        path: "Destruction",
        element: "Ice",
        img: "./src/img/Jingliu.png",
        releaseVersion: "1.4",
        phase: 1,
        reruns:[
            {
                version: "2.1",
                phase: 2,
                date:"2024-04-17 ~ 2024-05-07",
            },
        ],
        releaseDate: ["2023-10-11 ~ 2023-10-27"],
        character4star: ["Sampo", "Tingyun", "Qingque"],
        lightCone: "I Shall Be My Own Sword",
    },
    {
        title: "Sunset Clause",
        characterName: "Topaz e Dinheirinho",
        path: "Hunt",
        element: "Fire",
        img: "./src/img/Topaz.png",
        releaseVersion: "1.4",
        phase: 2,
        reruns:[
            {
                version: "2.2",
                phase: 1,
                date:"2024-05-07 ~ 2024-05-29",
            },
            {
                version: "2.5",
                phase: 2,
                date:"2024-10-02 ~ 2024-10-22",
            },
        ],
        releaseDate: ["2023-10-27 ~ 2023-11-15"],
        character4star: ["Guinaiffen", "Luka", "Sushang"],
        lightCone: "Worrisome, Blissful",
    },
    {
        title: "Bloom in Gloom",
        characterName: "Huohuo",
        path: "Abundance",
        element: "Wind",
        img: "./src/img/Huohuo.png",
        releaseVersion: "1.5",
        phase: 1,
        reruns:[
            {
                version: "2.4",
                phase: 1,
                date:"2024-07-30 ~ 2024-08-21",
            },
        ],
        releaseDate: ["2023-11-15 ~ 2023-12-06"],
        character4star: ["Dan Heng", "Arlan", "Serval"],
        lightCone: "Night of Fright",
    },
    {
        title: "Thorns of Scented Crown",
        characterName: "Argenti",
        path: "Erudition",
        element: "Physical",
        img: "./src/img/Argenti.png",
        releaseVersion: "1.5",
        phase: 2,
        reruns:[
            {
                version: "2.3",
                phase: 2,
                date:"2024-07-10 ~ 2024-07-30",
            },
        ],
        releaseDate: ["2023-12-06 ~ 2023-12-26"],
        character4star: ["Hanya", "Lynx", "Asta"],
        lightCone: "An Instant Before A Gaze",
    },
    {
        title: "Floral Triptych",
        characterName: "Ruan Mei",
        path: "Harmony",
        element: "Ice",
        img: "./src/img/RuanMei.png",
        releaseVersion: "1.6",
        phase: 1,
        reruns:[
            {
                version: "2.3",
                phase: 1,
                date:"2024-06-18 ~ 2024-07-10",
            },
        ],
        releaseDate: ["2023-12-26 ~ 2024-01-17"],
        character4star: ["7 de Março", "Tingyun", "Xueyi"],
        lightCone: "Past Self in Mirror",
    },
    {
        title: "Panta Rhei",
        characterName: "Dr Ratio",
        path: "Hunt",
        element: "Imaginary",
        img: "./src/img/DrRatio.png",
        releaseVersion: "1.6",
        phase: 2,
        reruns:[],
        releaseDate: ["2024-01-17 ~ 2024-02-05"],
        character4star: ["Sushang", "Natasha", "Hook"],
        lightCone: "Baptism of Pure Thought",
    },
    {
        title: "Ripples in Reflection",
        characterName: "Black Swan",
        path: "Nihility",
        element: "Wind",
        img: "./src/img/BlackSwan.png",
        releaseVersion: "2.0",
        phase: 1,
        reruns:[
            {
                version: "2.5",
                phase: 1,
                date:"2024-09-09 ~ 2024-10-02",
            },
        ],
        releaseDate: ["2024-02-05 ~ 2024-02-29"],
        character4star: ["Misha", "Guinaifen", "Tingyun"],
        lightCone: "Reforged Remembrance",
    },
    {
        title: "Sparkling Splendor",
        characterName: "Sparkle",
        path: "Harmony",
        element: "Quantum",
        img: "./src/img/Sparkle.png",
        releaseVersion: "2.0",
        phase: 2,
        reruns:[
            {
                version: "2.4",
                phase: 2,
                date:"2024-08-21 ~ 2024-09-09",
            },
        ],
        releaseDate: ["2024-02-29 ~ 2024-03-26"],
        character4star: ["Hanya", "Qingque", "Sampo"],
        lightCone: "Earthly Escapade",
    },
    {
        title: "Words of Yore",
        characterName: "Acheron",
        path: "Nihility",
        element: "Lightning",
        img: "./src/img/Acheron.png",
        releaseVersion: "2.1",
        phase: 1,
        reruns:[
            {
                version: "2.6",
                phase: 2,
                date:"2024-11-13 ~ 2024-12-03",
            },
        ],
        releaseDate: ["2024-03-26 ~ 2024-04-17"],
        character4star: ["Gallagher", "Pela", "Dan Heng"],
        lightCone: "Along the Passing Shore",
    },
    {
        title: "Gilded Imprisonment",
        characterName: "Aventurine",
        path: "Preservation",
        element: "Imaginary",
        img: "./src/img/Aventurine.png",
        releaseVersion: "2.1",
        phase: 2,
        reruns:[
            {
                version: "2.6",
                phase: 2,
                date:"2024-11-13 ~ 2024-12-03",
            },
        ],
        releaseDate: ["2024-04-17 ~ 2024-05-07"],
        character4star: ["Lynx", "Luka", "Serval"],
        lightCone: "Inherently Unjust Destiny",
    },
    {
        title: "Just Intonation",
        characterName: "Robin",
        path: "Harmony",
        element: "Physical",
        img: "./src/img/Robin.png",
        releaseVersion: "2.2",
        phase: 1,
        reruns:[
            {
                version: "2.5",
                phase: 1,
                date:"2024-09-09 ~ 2024-10-02",
            },
        ],
        releaseDate: ["2024-05-07 ~ 2024-05-29"],
        character4star: ["7 de Março", "Hanya", "Xueyi"],
        lightCone: "Flowing Nightglow",
    },
    {
        title: "Dusty Trail's Lone Star",
        characterName: "Boothill",
        path: "Hunt",
        element: "Physical",
        img: "./src/img/Boothill.png",
        releaseVersion: "2.2",
        phase: 2,
        reruns:[],
        releaseDate: ["2024-05-29 ~ 2024-06-18"],
        character4star: ["Pela", "Luka", "Hook"],
        lightCone: "Sailing Towards a Second Life",
    },
    {
        title: "Firefull Flyshine",
        characterName: "Firefly",
        path: "Destruition",
        element: "Fire",
        img: "./src/img/Firefly.png",
        releaseVersion: "2.3",
        phase: 1,
        reruns:[],
        releaseDate: ["2024-06-18 ~ 2024-07-10"],
        character4star: ["Gallagher", "Misha", "Xueyi"],
        lightCone: "Whereabouts Should Dreams Rest",
    },
    {
        title: "Lien on Life, Lease on Fate",
        characterName: "Jade",
        path: "Erudition",
        element: "Quantum",
        img: "./src/img/Jade.png",
        releaseVersion: "2.3",
        phase: 2,
        reruns:[],
        releaseDate: ["2024-07-10 ~ 2024-07-30"],
        character4star: ["Serval", "Natasha", "Asta"],
        lightCone: "Yet Hope Is Priceless",
    },
    {
        title: "Earth Hurled, Ether Curled",
        characterName: "Yunli",
        path: "Destruition",
        element: "Physical",
        img: "./src/img/Yunli.png",
        releaseVersion: "2.4",
        phase: 1,
        reruns:[],
        releaseDate: ["2024-07-30 ~ 2024-08-21"],
        character4star: ["Hanya", "Yukong", "Lynx"],
        lightCone: "Dance at Sunset",
    },
    {
        title: "Cauldron Contrivance",
        characterName: "Jiaoqiu",
        path: "Nihility",
        element: "Fire",
        img: "./src/img/Jiaoqiu.png",
        releaseVersion: "2.4",
        phase: 2,
        reruns:[],
        releaseDate: ["2024-08-21 ~ 2024-09-09"],
        character4star: ["Hook", "Guinaifen", "Arlan"],
        lightCone: "Those Many Springs",
    },
    {
        title: "Stormrider's Bolt",
        characterName: "Feixiao",
        path: "Hunt",
        element: "Wind",
        img: "./src/img/Feixiao.png",
        releaseVersion: "2.5",
        phase: 1,
        reruns:[],
        releaseDate: ["2024-09-09 ~ 2024-10-02"],
        character4star: ["Asta", "Luka", "Moze"],
        lightCone: "I Venture Forth to Hunt",
    },
    {
        title: "Let Scent Sink In",
        characterName: "Lingsha",
        path: "Abundance",
        element: "Fire",
        img: "./src/img/Lingsha.png",
        releaseVersion: "2.5",
        phase: 2,
        reruns:[],
        releaseDate: ["2024-- ~ 2024--"],
        character4star: ["Guinaifen", "Misha", "Natasha"],
        lightCone: "Scent Alone Stays True",
    },
    {
        title: "Eyes of a Ninja",
        characterName: "Rappa",
        path: "Erudition",
        element: "Imaginary",
        img: "./src/img/Rappa.png",
        releaseVersion: "2.6",
        phase: 1,
        reruns:[],
        releaseDate: ["2024-10-22 ~ 2024-11-13"],
        character4star: ["Lynx", "Xueyi", "Yukong"],
        lightCone: "Ninjutsu Inscription: Dazzling Evilbreaker",
    },
    {
        title: "Only Reruns",
        characterName: "Only Reruns",
        path: "",
        element: "",
        img: "./src/img/beginner.png",
        releaseVersion: "2.6",
        phase: 2,
        reruns:[],
        releaseDate: ["2024-11-13 ~ 2024-12-03"],
        character4star: ["7 de Março", "Pela", "Sampo"],
        lightCone: "",
    },
]
